# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-30 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='sBB', max_length=300, verbose_name='课程类别'),
        ),
    ]
