# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-03 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_is_banne5r'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_banne5r',
            new_name='is_banner',
        ),
    ]
