# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-03 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190603_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.CharField(max_length=300, verbose_name='课程述'),
        ),
    ]
